default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  database: <%= ENV.fetch("DATABASE_NAME", "edge_detection_default") %>

development:
  <<: *default
  database: edge_detection_development

test:
  <<: *default
  database: edge_detection_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  database: edge_detection_cable

queue:
  <<: *default
  database: edge_detection_queue

cache:
  <<: *default
  database: edge_detection_cache
